# Describe VMs
MACHINES = {
  # VM name "kernel update"
  :"kernel-update" => {
              # VM box
              :box_name => ENV['MY_BOX'] || "centos/7",
              # VM CPU count
              :cpus => 3,
              # VM RAM size (Mb)
              :memory => 7000,
              # networks
              :net => [],
              # forwarded ports
              :forwarded_port => [],
              # Provider
              :provider => ENV['MY_PROVIDER'] || "libvirt"
            }
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
    if boxconfig[:provider]=="virtualbox"
      config.vm.synced_folder ".", "/vagrant", type: "virtualbox", SharedFoldersEnableSymlinksCreate: "false"
    else
      config.vm.synced_folder ".", "/vagrant", disabled: true
    end
    # Apply VM config
    config.vm.define boxname do |box|
      # Set VM base box and hostname    
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      # Additional network config if present
      if boxconfig.key?(:net)
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
      end
      # Port-forward config if present
      if boxconfig.key?(:forwarded_port)
        boxconfig[:forwarded_port].each do |port|
          box.vm.network "forwarded_port", port
        end
      end
      # VM resources config
      box.vm.provider boxconfig[:provider] do |v|
        # Set VM RAM size and CPU count
        v.memory = boxconfig[:memory]
        v.cpus = boxconfig[:cpus]
        if boxconfig[:provider]=="virtualbox"
          #v.customize ["storageattach", :id, "--storagectl", "IDE Controller", "--port", "1", "--device", "0", "--type", "dvddrive", "--medium", "/usr/share/virtualbox/VBoxGuestAdditions.iso"]
          v.customize ["modifyvm", :id, "--vrde", "on"]
          v.customize ["modifyvm", :id, "--vrdeport", "3940"]
          v.customize ["modifyvm", :id, "--vrdeaddress", "127.0.0.1"]
        end
      end
    end
  end
end
